version: 2.1

orbs:
  node: circleci/node@5.0.2
  coveralls: coveralls/coveralls@2.0.0

jobs:
  say-hello:

    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - run:
          name: "Team-techsmith-e-commerce tests"
          command: "echo Hello, World!"

  Test_and_Send_Coverage: 
    executor: node/default 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install
          name: Install Dependencies
          environment: 
            DB_USER:  postgres
            DB_PASSWORD: Musanzeyacu
            DB_NAME: postgres
            DB_HOST: db.mlyoiqwupkrgbbazipqu.supabase.co
            DB_PORT: 5432
            EMAIL: mudakikwaaimable05@outlook.com
            PASSWORD: Workhard
            SERVICE: hotmail
            JWT_SECRET: parfaite
            APP_URL: http://localhost:4000
            COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN  
      - run:
          command: npm ci
          name: Install Packages
      # - run: npm run start & npm run test
      # - run: sleep 10
      - run:
          command: npm run test
          name: Run tests
      - run: 
          name: code-coverage
          command: npm run coverage
      - coveralls/upload

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  Test_and_Covarage:
    jobs:
      - Test_and_Send_Coverage